{% set name = "causal-testing-framework" %}
{% set version = "14.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/causal_testing_framework-{{ version }}.tar.gz
  sha256: bd843d9a02f3ccff9fe028e5d7309a8dc8e80545405ba7d3b34a752b6c1b17e8

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python
    - lifelines <=0.28.0                 # [py==310]
    - lifelines >=0.30.0,<0.31.dev0      # [py>310]
    - networkx >=3.4,<3.5
    - numpy >=1.26.0,<2.0                # [py==310] 
    - numpy >=1.26.0,<=2.2.0             # [py>310]
    - pandas >=2.1,<3                    
    - scikit-learn >=1.4,<2.dev0
    - scipy >=1.12.0,<1.14               # [py==310]
    - scipy >=1.12.0,<=1.16.2            # [py>310]
    - statsmodels >=0.14,<1.dev0
    - tabulate >=0.9,<1.dev0
    - pydot >=2.0                       
    - pygad >=3.3,<4.dev0
    - deap >=1.4.1,<1.5.dev0
    - sympy >=1.13.1,<1.14.dev0
    - pyarrow >=19.0.1,<19.1.dev0
    - fastparquet >=2024.11.0,<2024.12.dev0
    - tqdm >=4.67.1,<4.68.dev0

test:
  imports:
    - causal_testing
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/CITCOM-project/CausalTestingFramework
  summary: A causal inference-driven framework for functional black-box testing of complex software.
  description: |
    The Causal Testing Framework is composed of a causal inference-driven architecture designed for functional black-box testing. 
    It leverages graphical causal inference (CI) techniques to specify and evaluate software behaviour from a black-box perspective. 
    Within this framework, causal directed acyclic graphs (DAGs) are used to represent the expected cause–effect relationships between 
    the inputs and outputs of the system under test, supported by mathematical foundations for designing statistical procedures that 
    enable causal inference. Each causal test case targets the causal effect of a specific intervention on the system under test--that is, 
    a deliberate modification to the input configuration expected to produce a corresponding change in one or more outputs.
  doc_url: https://causal-testing-framework.readthedocs.io/
  dev_url: https://github.com/CITCOM-project/CausalTestingFramework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - f-allian
    - jmafoster1
